In [1]:
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [4]:
#Create a sequential model and add a layer with relu activation
model = Sequential()
model.add(layers.Dense(2, activation="relu"))

In [6]:
#We've added one layer
print(len(model.layers))

1


In [8]:
#the model doesn't have any inputs yet, so there are no weights and this throws an error.
model.weights

[]

In [10]:
#give a simple input to the model
x=tf.ones((1,4))
y=model(x)

In [12]:
#Now there are model weights!
model.weights

[<Variable path=sequential/dense/kernel, shape=(4, 2), dtype=float32, value=[[-0.48590326  0.6781306 ]
  [-0.76287556  0.54305077]
  [ 0.31350446  0.26014185]
  [ 0.07826877  0.08137918]]>,
 <Variable path=sequential/dense/bias, shape=(2,), dtype=float32, value=[0. 0.]>]

In [14]:
#and you can see the summary of the model. There is one layer with the output shape of "2" that we entered above
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (1, 2)                      │              10 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 10 (40.00 B)

 Trainable params: 10 (40.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
#Make a new model and this time start with an input shape
model = Sequential()
model.add(layers.Dense(2, activation="relu", input_shape=(4,)))
model.add(layers.Dense(3))
model.add(layers.Dense(4))

C:\Users\Olufemi\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [20]:
#this model also has more layers
print(len(model.layers))

3


In [22]:
#model weights are there even though the model hasn't been run yet
model.weights

[<Variable path=sequential_1/dense_1/kernel, shape=(4, 2), dtype=float32, value=[[-0.17994356  0.42002273]
  [-0.24972034  0.7761073 ]
  [ 0.8313203   0.776304  ]
  [ 0.9045596   0.95079017]]>,
 <Variable path=sequential_1/dense_1/bias, shape=(2,), dtype=float32, value=[0. 0.]>,
 <Variable path=sequential_1/dense_2/kernel, shape=(2, 3), dtype=float32, value=[[ 0.54664266 -0.23545164 -0.2440545 ]
  [-0.52081245  0.24875855  0.98765755]]>,
 <Variable path=sequential_1/dense_2/bias, shape=(3,), dtype=float32, value=[0. 0. 0.]>,
 <Variable path=sequential_1/dense_3/kernel, shape=(3, 4), dtype=float32, value=[[ 0.5412369  -0.67922616  0.30220628  0.785514  ]
  [-0.63925785 -0.29746604 -0.33194405 -0.76740336]
  [-0.6623068  -0.5136022   0.8017843   0.83782434]]>,
 <Variable path=sequential_1/dense_3/bias, shape=(4,), dtype=float32, value=[0. 0. 0. 0.]>]

In [24]:
#Now the model shows three layers, each of the type entered above, but there are no inputs yet.
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                      │ (None, 2)                   │              10 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 3)                   │               9 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 4)                   │              16 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 35 (140.00 B)

 Trainable params: 35 (140.00 B)

 Non-trainable params: 0 (0.00 B)